default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: banta_development

test:
  <<: *default
  database: banta_test

production:
  <<: *default
  database: banta_production
  username: 
  password: